### ISSUE TITLE
bug - timer content shifting

### ISSUE THREAD

**Issue by sandeshShahapur** [AnanteshG/Contest-Hub#3]
the countdown of an event shifts in width due to varying character widths. 

one fix is to use monospace font family.

without removing whitespaces:
![image](https://github.com/user-attachments/assets/191a1915-98dd-4b4b-b653-85c1476724fb)

with removing whitespaces:
![image](https://github.com/user-attachments/assets/78989f75-51ff-4208-acb2-a3c7061bb834)

**Comment by AnanteshG** [comment]
It looks like the images didn't upload correctly. Could you please resend them?

**Comment by sandeshShahapur** [comment]
updated

**Comment by AnanteshG** [comment]
I have tried setting a fixed width of 160px for the countdown boxes so that the box size doesn't change due to varying widths of the numbers, and it looks something like this. I personally think that this looks a bit odd than the current one.
![image](https://github.com/user-attachments/assets/0c2c1e2c-57a5-44b8-b4f6-ee509b2afda2)

**Comment by sandeshShahapur** [comment]
i feel monospace font is a better aesthetic solution. i will leave that choice to you, and letting this issue be open for new people to contribute would be nice as i agree on it being a good first issue

**Comment by AnanteshG** [comment]
Okay!
